

language: go
go_import_path: github.com/qmuntal/opc

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x

env:
  - GO111MODULE=on

notifications:
  - email: false

before_script:
  - go get -u github.com/mattn/goveralls
  - go get -u golang.org/x/tools/cmd/cover
  - go get -t -v .

script:
  - go test . -coverprofile=coverage.out -race -timeout=5s
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
